using System.Collections;
using System.Collections.Generic;
using Unity.Android.Gradle;
using UnityEngine;

//TODO:効果率変更すべし

public class ElementChart
{
    //static float[][] chart =
    //{
    //               攻撃\防御   人   ス   メ   獣   物    悪   機   鳥   ドラ ゾン  呪  自然  神
    ///*人系*/      new float[] { 1f, 1f,  0f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f},
    ///*スライム系*/new float[] {  1f,  1.25f,0f,  1f,  1f,  1f,  1f,  1f, 1f,  1f,  1f,  1f,  1f},
    ///*メタル系*/new float[]   {  1f,  1f,  0f, 1f, 1f,  1f,  1f,  1f, 1f,  1f,  1f,  1f,  1f},
    ///*獣系*/new float[]       {  1f,  1f,  0f,  1.25f,1f,  1f,  1f,  1f, 1f,  1f,  1f,  1f,  1f},
    ///*物質系*/new float[]     {  1f,  1f,  0f,  1f,  1.25f,1f,  1f,  1f, 1f,  1f,  1f,  1f,  1f},
    ///*悪魔系*/new float[]     {  1f,  1f,  0f,  1f,  1f,  1.25f,1f,  1f, 1f,  1f,  1f,  1f,  1f},
    ///*機械系*/new float[]     {  1f,  1f,  0f,  1f,  1f,  1f,  1.25f,1f, 1f,  1f,  1f,  1f,  1f},
    ///*鳥系*/new float[]       {  1f,  1f,  0f,  1f,  1f,  1f,  1f, 1.25f,1f,  1f,  1f,  1f,  1f},
    ///*ドラゴン系*/new float[] {  1f,  1f,  0f,  1f,  1f,  1f,  1f,  1f, 1.25f,1f,  1f,  1f,  1f},
    ///*ゾンビ系*/new float[]   {  1f,  1f,  0f,  1f,  1f,  1f,  1f,  1f,  1f, 1.25f,1f,  1f,  1f},
    ///*呪術師系*/new float[]   {  1f,  1f,  0f,  1f,  1f,  1f,  1f,  1f,  1f,  1f, 1.25f,1f,  1f},
    ///*自然系*/new float[]     {  1f,  1f,  0f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f, 1.25f,1f}, <summary>
    /// *人系*/      new float[] { 1f, 1f,  0f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f},
    /// </summary>
    /// <param name="attackType"></param>
    /// <param name="deffenseType"></param>
    /// <returns></returns>        /*???系(神)new float[]  {  1f,  1f,  0f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1f,  1.25f},*/
    //};//13x13の二次元配列
    //Ex:ゾンビ系の攻撃(ゾンビ斬り)➤ゾンビ系に1.25倍のダメージ

    //魔法ver
    public static Dictionary<(BattleMagicElements attackType, EnemyBase.EnemyType enemyType), float> MagicEffectivenessChart = new Dictionary<(BattleMagicElements attackType, EnemyBase.EnemyType enemyType), float>
        {
            //(攻撃属性,防御属性)=>相性
            //無属性
            {(BattleMagicElements.None,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.None,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.None, EnemyBase.EnemyType.God), 1f},
            //メラ属性
            {(BattleMagicElements.Mela,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Mela,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Beast), 1.25f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Devil), 1.25f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Machine), 0.8f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Bird), 1.25f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Dragon), 0.5f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Zombie), 1.5f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Warlock), 0.6f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.Natural), 0.9f},
            {(BattleMagicElements.Mela, EnemyBase.EnemyType.God), 1.2f},
            //メラ属性
            {(BattleMagicElements.Ghila,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Ghila,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Beast), 1.25f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Devil), 1.25f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Machine), 0.8f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Bird), 1.25f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Dragon), 0.5f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Zombie), 1.5f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Warlock), 0.6f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.Natural), 0.9f},
            {(BattleMagicElements.Ghila, EnemyBase.EnemyType.God), 1f},
            //ヒャド属性
            {(BattleMagicElements.Ice,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Ice,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Beast), 0.5f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Machine), 0.8f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Dragon), 0.5f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Warlock), 0.6f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Ice, EnemyBase.EnemyType.God), 1f},
            //バギ属性
            {(BattleMagicElements.Wind,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Wind,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Bird), 1.4f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Dragon), 0.7f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Warlock), 0.7f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.Natural), 0.7f},
            {(BattleMagicElements.Wind, EnemyBase.EnemyType.God), 1f},
            //イオ属性
            {(BattleMagicElements.Io,EnemyBase.EnemyType.Human),1.1f},
            {(BattleMagicElements.Io,EnemyBase.EnemyType.Slime),1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Beast), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Material), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Devil), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Machine), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Bird), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Dragon), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Zombie), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Warlock), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.Natural), 1.1f},
            {(BattleMagicElements.Io, EnemyBase.EnemyType.God), 1f},
            //デイン属性
            {(BattleMagicElements.Electric,EnemyBase.EnemyType.Human),1.1f},
            {(BattleMagicElements.Electric,EnemyBase.EnemyType.Slime),1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Beast), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Material), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Devil), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Machine), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Bird), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Dragon), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Zombie), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Warlock), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.Natural), 1.1f},
            {(BattleMagicElements.Electric, EnemyBase.EnemyType.God), 1f},
            //メガンテ属性
            {(BattleMagicElements.Explosion,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Explosion,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Explosion, EnemyBase.EnemyType.God), 0},
            //ザキ属性
            {(BattleMagicElements.Death,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Death,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Devil), 0.8f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Machine), 0f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Zombie), 0},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Death, EnemyBase.EnemyType.God), 0},
            //マヌーサ属性
            {(BattleMagicElements.Blind,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Blind,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Blind, EnemyBase.EnemyType.God), 0},
            //ラリホー属性
            {(BattleMagicElements.Sleep,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Sleep,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Machine), 0},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Zombie), 0},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Sleep, EnemyBase.EnemyType.God), 0},
            //メダパニ属性
            {(BattleMagicElements.Confuse,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Confuse,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Confuse, EnemyBase.EnemyType.God), 0},
            //二フラム属性
            {(BattleMagicElements.Bunish,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Bunish,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Bunish, EnemyBase.EnemyType.God), 0},
            //マホトラ属性
            {(BattleMagicElements.MPabsorb,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.MPabsorb,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.MPabsorb, EnemyBase.EnemyType.God), 0},
            //バフ魔法
            {(BattleMagicElements.Buff,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Buff,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Buff, EnemyBase.EnemyType.God), 1f},
            //デバフ魔法
            {(BattleMagicElements.Debuff,EnemyBase.EnemyType.Human),1f},
            {(BattleMagicElements.Debuff,EnemyBase.EnemyType.Slime),1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Metal), 0},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Beast), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Material), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Devil), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Machine), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Bird), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Dragon), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Zombie), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Warlock), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.Natural), 1f},
            {(BattleMagicElements.Debuff, EnemyBase.EnemyType.God), 0.5f},
        };
    public static float MagicGetEffectiveness(BattleMagicElements attackType, EnemyBase.EnemyType enemyType)
    {
        //上のDictionaryから相性を取得して返す
        if (MagicEffectivenessChart.ContainsKey((attackType, enemyType)))
        {
            return MagicEffectivenessChart[(attackType, enemyType)];
        }
        else
        {
            return 1f;
        }
    }
    //とくぎver
    public static Dictionary<(Skill.BattleSkillType attackType, EnemyBase.EnemyType enemyType), float> SkillEffectivenessChart = new Dictionary<(Skill.BattleSkillType attackType, EnemyBase.EnemyType), float>
    {
        //(攻撃属性,防御属性)=>相性
            //無属性
            {(Skill.BattleSkillType.None,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.None,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.None, EnemyBase.EnemyType.God), 1f},
            //メラ属性
            {(Skill.BattleSkillType.Mela,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Mela,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Mela, EnemyBase.EnemyType.God), 1f},
            //ギラ属性
            {(Skill.BattleSkillType.Gila,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Gila,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Gila, EnemyBase.EnemyType.God), 1f},
            //ヒャド属性
            {(Skill.BattleSkillType.Ice,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Ice,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Ice, EnemyBase.EnemyType.God), 1f},
            //バギ属性
            {(Skill.BattleSkillType.Wind,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Wind,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Wind, EnemyBase.EnemyType.God), 1f},
            //イオ属性
            {(Skill.BattleSkillType.Io,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Io,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Io, EnemyBase.EnemyType.God), 1f},
            //デイン属性
            {(Skill.BattleSkillType.Thunder,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Thunder,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Thunder, EnemyBase.EnemyType.God), 1f},
            //二倍の攻撃力(せいけんづき)
            {(Skill.BattleSkillType.Twice,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Twice,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Twice, EnemyBase.EnemyType.God), 1f},
            //自分にもダメージ受ける攻撃(たいあたり、もろばぎり)
            {(Skill.BattleSkillType.Moroba,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Moroba,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Moroba, EnemyBase.EnemyType.God), 1f},
            //光属性
            {(Skill.BattleSkillType.Holy,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Holy,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Holy, EnemyBase.EnemyType.God), 1f},
            //ドラゴン特化
            {(Skill.BattleSkillType.Dragon,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Dragon,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Dragon, EnemyBase.EnemyType.God), 1f},
            //メタル系特化
            {(Skill.BattleSkillType.Metal,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Metal,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Metal, EnemyBase.EnemyType.God), 1f},
            //浮遊している敵に特化
            {(Skill.BattleSkillType.Hober,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Hober,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Hober, EnemyBase.EnemyType.God), 1f},
            //みなごろし
            {(Skill.BattleSkillType.Random,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Random,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Random, EnemyBase.EnemyType.God), 1f},
            //会心系(まじんぎり)
            {(Skill.BattleSkillType.Critical,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Critical,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Critical, EnemyBase.EnemyType.God), 1f},
            //いしつぶて
            {(Skill.BattleSkillType.Group,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Group,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Group, EnemyBase.EnemyType.God), 1f},
            //ムーンサルト、さみだれ斬り、ばくれつけん
            {(Skill.BattleSkillType.GradualDecrease,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.GradualDecrease,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.GradualDecrease, EnemyBase.EnemyType.God), 1f},
            //しゃくねつ系
            {(Skill.BattleSkillType.Flame,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Flame,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Flame, EnemyBase.EnemyType.God), 1f},
            //冷たい息系
            {(Skill.BattleSkillType.Blizzard,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Blizzard,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Blizzard, EnemyBase.EnemyType.God), 1f},
            //しのおどり、じわれ
            {(Skill.BattleSkillType.Death,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Death,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Death, EnemyBase.EnemyType.God), 1f},
            //ともえなげ,つきとばし
            {(Skill.BattleSkillType.Wipe,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Wipe,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Zombie), 0f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Wipe, EnemyBase.EnemyType.God), 0f},
            //ねる、あまいいき
            {(Skill.BattleSkillType.Sleep,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Sleep,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Sleep, EnemyBase.EnemyType.God), 1f},
            //ハッスルダンス、めいそう
            {(Skill.BattleSkillType.Heal,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Heal,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Heal, EnemyBase.EnemyType.God), 1f},
            //メダパニダンス
            {(Skill.BattleSkillType.Confuse,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Confuse,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Confuse, EnemyBase.EnemyType.God), 1f},
            //やけつくいき
            {(Skill.BattleSkillType.Palanoyze,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Palanoyze,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Palanoyze, EnemyBase.EnemyType.God), 1f},
            //すなけむり
            {(Skill.BattleSkillType.Blind,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Blind,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Blind, EnemyBase.EnemyType.God), 1f},
            //なめまわし、あしばらい等
            {(Skill.BattleSkillType.Break,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Break,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Break, EnemyBase.EnemyType.God), 1f},
            //ぶきみなひかり
            {(Skill.BattleSkillType.MagicResistanceDecrease,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.MagicResistanceDecrease, EnemyBase.EnemyType.God), 1f},
            //ふしぎなおどり
            {(Skill.BattleSkillType.MPDecrease,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.MPDecrease,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.MPDecrease, EnemyBase.EnemyType.God), 1f},
            //マホトラおどり、
            {(Skill.BattleSkillType.MPAbcorb,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.MPAbcorb,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.MPAbcorb, EnemyBase.EnemyType.God), 1f},
            //いてつくはどう
            {(Skill.BattleSkillType.ItetsukuHadou,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.ItetsukuHadou,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.ItetsukuHadou, EnemyBase.EnemyType.God), 1f},
            //きあいため、ちからため
            {(Skill.BattleSkillType.NextDamageUp,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.NextDamageUp,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.NextDamageUp, EnemyBase.EnemyType.God), 1f},
            //まねまね
            {(Skill.BattleSkillType.ManeMane,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.ManeMane,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.ManeMane, EnemyBase.EnemyType.God), 1f},
            //はねかえし
            {(Skill.BattleSkillType.BreathReflect,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.BreathReflect,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.BreathReflect, EnemyBase.EnemyType.God), 1f},
            //みかわしきゃく
            {(Skill.BattleSkillType.DodgeUp,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.DodgeUp,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.DodgeUp, EnemyBase.EnemyType.God), 1f},
            //におうだち
            {(Skill.BattleSkillType.NiohDachi,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.NiohDachi,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.NiohDachi, EnemyBase.EnemyType.God), 1f},
            //だいぼうぎょ
            {(Skill.BattleSkillType.Daibougyo,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Daibougyo,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Daibougyo, EnemyBase.EnemyType.God), 1f},
            //もうどくのきり
            {(Skill.BattleSkillType.SuperPoison,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.SuperPoison,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.SuperPoison, EnemyBase.EnemyType.God), 1f},
            //つなみとか
            {(Skill.BattleSkillType.Water,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Water,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Water, EnemyBase.EnemyType.God), 1f},
            //がんせきおとし
            {(Skill.BattleSkillType.Rock,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Rock,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Metal), 0},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Rock, EnemyBase.EnemyType.God), 1f},
            //そせい(せいれいのうた)
            {(Skill.BattleSkillType.Revival,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.Revival,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Metal), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.Revival, EnemyBase.EnemyType.God), 1f},
            //しっぷうづき
            {(Skill.BattleSkillType.FirstAttack,EnemyBase.EnemyType.Human),1f},
            {(Skill.BattleSkillType.FirstAttack,EnemyBase.EnemyType.Slime),1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Metal), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Beast), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Material), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Devil), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Machine), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Bird), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Dragon), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Zombie), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Warlock), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.Natural), 1f},
            {(Skill.BattleSkillType.FirstAttack, EnemyBase.EnemyType.God), 1f},
        };

        public static float SkillGetEffectiveness(Skill.BattleSkillType attackType, EnemyBase.EnemyType enemyType)
    {
        //上のDictionaryから相性を取得して返す
        if (SkillEffectivenessChart.ContainsKey((attackType, enemyType)))
        {
            return SkillEffectivenessChart[(attackType, enemyType)];
        }
        else
        {
            return 1f;
        }
    }
    }
